"""Manufacturer name normalisation for SSR/SEO output.

Mirrors frontend/src/utils/text.js `formatManufacturer`.
Strips juridical-form prefixes/suffixes and replaces known long names
with canonical brand names (e.g. "АО КРКА, Д.Д., НОВО МЕСТО" → "KRKA").

AUTOGENERATED — do not edit. Source: frontend/src/utils/text.js.
Regenerate by running: node /app/gen_python_port.mjs > backend/api/text_format.py
"""
import re
import unicodedata

LEGAL_FORMS = [
    "ОАО",
    "ООО",
    "ЗАО",
    "ПАО",
    "НАО",
    "АО",
    "ОДО",
    "ИП",
    "ФГУП",
    "ФГБУ",
    "ГБУ",
    "ГУП",
    "ГП",
    "ФКП",
    "ПФК",
    "НПО",
    "НПП",
    "НПК",
    "ПКФ",
    "ХФК",
    "ФП",
    "OOO",
    "AO",
    "OAO",
    "PAO",
]

FOREIGN_LEGAL_TOKENS = [
    "Д.Д.",
    "Д.О.О.",
    "СП. З.О.О.",
    "З.О.О.",
    "Н.В.",
    "С.А.",
    "С.А.У.",
    "С.П.А.",
    "С.Р.Л.",
    "С.Р.О.",
    "С.Л.",
    "С.Л.У.",
    "С.А.С.",
    "С.Л.Р.",
    "К.С.",
    "К.Г.",
    "К.Г.А.А.",
    "М.Б.Х.",
    "К.Б.",
    "А.Д.",
    "А.О.",
    "А.Ш.",
    "А.С.",
    "А.Е.",
    "А.В.Е.",
    "А.Б.",
    "Б.В.",
    "Н.В.",
    "П.К.",
    "Л.Л.С.",
    "ГМБХ",
    "ГмбХ",
    "ЛТД.",
    "ЛТД",
    "ЛТДА.",
    "ЛТДА",
    "СПА",
    "АГ",
    "СА",
    "СЕ",
    "ИНК",
    "ИНК.",
    "КГ",
    "ОГ",
    "НФГ.",
    "НФГ",
    "ЛЛС",
    "ЛЛК",
    "МБХ",
    "МбХ",
    "ПВТ.",
    "ПВТ",
    "ПЛК",
    "ПЛК.",
    "ПТЕ.",
    "ПТЕ",
    "КО.",
    "КО",
    "ШИРКЕТИ",
    "А.Ш.",
    "АНОНИМ",
    "ТИДЖ.",
    "ТИДЖ",
    "ПРАЙВЕТ",
    "ЛИМИТЕД",
    "ИНДАСТРИЗ",
    "ЛАБОРАТОРИЗ",
    "ЛАБОРАТОРИС",
    "ЛАБОРАТОРИЕС",
    "ИНТЕРНЕШНЛ",
    "ХЕЛСКЭР",
    "ХЕЛСКЕА",
    "ХОЛДИНГ",
    "ГРУПП",
    "ГРУП",
    "КОМПАНИ",
    "ИНКОРПОРЕЙТЕД",
    "САНАЙИ",
    "ТИДЖАРЕТ",
    "ИЛАЧ",
    "GMBH",
    "GMBH.",
    "LTD.",
    "LTD",
    "LLC",
    "LLC.",
    "INC.",
    "INC",
    "PLC",
    "PLC.",
    "BV",
    "B.V.",
    "AG",
    "A.G.",
    "SA",
    "S.A.",
    "SAU",
    "S.A.U.",
    "SARL",
    "S.A.R.L.",
    "SRL",
    "S.R.L.",
    "SPA",
    "S.P.A.",
    "KG",
    "KGAA",
    "CO.",
    "CO",
    "AB",
    "OY",
    "KK",
    "KFT",
    "COMPANY",
    "COMPAGNIE",
    "CORP",
    "CORPORATION",
    "INCORPORATED",
    "PVT.",
    "PVT",
    "LTDA",
    "LTDA.",
    "PTE.",
    "PTE",
    "SAS",
    "S.A.S.",
    "ARZNEIMITTEL",
    "PHARMA",
    "PHARMACEUTICAL",
    "PHARMACEUTICALS",
    "HEALTHCARE",
    "LABORATORIES",
    "LABORATORIS",
    "INDUSTRIES",
    "INDUSTRY",
    "HOLDING",
    "GROUP",
    "TRADING",
    "INTERNATIONAL",
]

# Tokens that are SAFE to strip even if they are the last word.
# Excludes PHARMA/HEALTHCARE/LABORATORIES/INDUSTRIES/HOLDING/GROUP/INTERNATIONAL
# (they are often part of the brand itself, e.g. "Sun Pharma").
_UNSAFE_TRAIL_RE = re.compile(
    r"(PHARMA|HEALTHCARE|LABORATOR|INDUSTR|HOLDING|GROUP|TRADING|INTERNATIONAL"
    r"|КОМПАНИ|ИНДАСТРИЗ|ЛАБОРАТОРИ|ИНТЕРНЕШНЛ|ХОЛДИНГ|ГРУПП|ХЕЛСК"
    r"|COMPANY|COMPAGNIE|ARZNEIMITTEL|PHARMACEUTICAL)",
    re.IGNORECASE,
)
SAFE_TRAIL = [t for t in FOREIGN_LEGAL_TOKENS if not _UNSAFE_TRAIL_RE.search(t)]

# Order matters — more specific patterns first.
BRAND_OVERRIDES = [
    (re.compile("(^|[\\s,])КРКА($|[\\s,])", re.IGNORECASE), "KRKA"),
    (re.compile("РЕКИТТ\\s+БЕНКИЗЕР", re.IGNORECASE), "Reckitt Benckiser"),
    (re.compile("ГЕДЕОН\\s+РИХТЕР", re.IGNORECASE), "Gedeon Richter"),
    (re.compile("САНОФИ(-АВЕНТИС)?(?![А-Я])", re.IGNORECASE), "Sanofi"),
    (re.compile("ОПЕЛЛА\\s+ХЕЛСК", re.IGNORECASE), "Opella Healthcare"),
    (re.compile("НОВАРТИС", re.IGNORECASE), "Novartis"),
    (re.compile("(ТАКЕДА|НИКОМЕД)", re.IGNORECASE), "Takeda"),
    (re.compile("ПФАЙЗЕР", re.IGNORECASE), "Pfizer"),
    (re.compile("ГЛАКСОСМИТКЛЯЙН|GLAXOSMITHKLINE|GSK", re.IGNORECASE), "GSK"),
    (re.compile("ХЕЙЛКАЙР|ХЭЛЕОН|HALEON", re.IGNORECASE), "Haleon"),
    (re.compile("(ЯНССЕН|КЕНВЬЮ|KENVUE)", re.IGNORECASE), "Kenvue"),
    (re.compile("БЕРИНГЕР\\s+ИНГЕЛЬХАЙМ", re.IGNORECASE), "Boehringer Ingelheim"),
    (re.compile("ШТАДА|STADA|НИЖФАРМ", re.IGNORECASE), "Stada"),
    (re.compile("(ЮНИК\\s+ФАРМАСЬЮТИКАЛ|ЦИПЛА|CIPLA)", re.IGNORECASE), "Cipla"),
    (re.compile("ТЕВА(?![А-Я])|САНДОЗ", re.IGNORECASE), "Teva"),
    (re.compile("АСТРАЗЕНЕКА|ASTRAZENECA", re.IGNORECASE), "AstraZeneca"),
    (re.compile("БАЙЕР|BAYER", re.IGNORECASE), "Bayer"),
    (re.compile("ЭББОТТ|ABBOTT", re.IGNORECASE), "Abbott"),
    (re.compile("БИОНОРИКА|BIONORICA", re.IGNORECASE), "Bionorica"),
    (re.compile("КРЕВЕЛЬ\\s+МОЙЗЕЛЬБАХ|KREWEL", re.IGNORECASE), "Krewel Meuselbach"),
    (re.compile("УРСАФАРМ|URSAPHARM", re.IGNORECASE), "Ursapharm"),
    (re.compile("МАТЕРИА\\s+МЕДИКА", re.IGNORECASE), "Materia Medica"),
    (re.compile("ФИРН\\s+М", re.IGNORECASE), "Фирн-М"),
    (re.compile("ЦИТОМЕД", re.IGNORECASE), "Цитомед"),
    (re.compile("СОФАРИМЕКС", re.IGNORECASE), "Sofarimex"),
    (re.compile("(^|[\\s,])МЕРК(\\s+КГАА|\\s+ШАРП|$|[\\s,])", re.IGNORECASE), "Merck"),
    (re.compile("ФАРМСТАНДАРТ", re.IGNORECASE), "Фармстандарт"),
    (re.compile("(^|\\s)ОЗОН(\\s+ФАРМ)?($|\\s|,)", re.IGNORECASE), "Озон"),
    (re.compile("КАНОНФАРМА", re.IGNORECASE), "Канонфарма"),
    (re.compile("(^|[\\s,])АКРИХИН($|[\\s,])", re.IGNORECASE), "Акрихин"),
    (re.compile("БИОХИМИК", re.IGNORECASE), "Биохимик"),
    (re.compile("ВЕЛФАРМ", re.IGNORECASE), "Велфарм"),
    (re.compile("АВВА\\s+РУС", re.IGNORECASE), "AVVA RUS"),
    (re.compile("НПО\\s+МИКРОГЕН|МИКРОГЕН", re.IGNORECASE), "Микроген"),
    (re.compile("ОТИСИФАРМ|ОТЦИФАРМ|ОТЦФАРМ", re.IGNORECASE), "Otcpharm"),
    (re.compile("(^|[\\s,])ВЕРТЕКС($|[\\s,])", re.IGNORECASE), "Vertex"),
    (re.compile("ПФК\\s+ОБНОВЛЕНИЕ|ОБНОВЛЕНИЕ\\s+ПФК|(^|\\s)ОБНОВЛЕНИЕ(\\s|$)", re.IGNORECASE), "Renewal"),
    (re.compile("(^|[\\s,])БИОКАД($|[\\s,])|BIOCAD", re.IGNORECASE), "BIOCAD"),
    (re.compile("(^|[\\s,])Р-ФАРМ($|[\\s,])|R-PHARM", re.IGNORECASE), "R-Pharm"),
    (re.compile("(^|[\\s,])ГЕНЕРИУМ($|[\\s,])|GENERIUM", re.IGNORECASE), "Generium"),
    (re.compile("(^|[\\s,])НАТИВА($|[\\s,])|NATIVA", re.IGNORECASE), "Nativa"),
    (re.compile("(^|[\\s,])ФАРМАСИНТЕЗ|PHARMASYNTEZ", re.IGNORECASE), "Pharmasyntez"),
    (re.compile("НОВО\\s+НОРДИСК|NOVO\\s+NORDISK", re.IGNORECASE), "Novo Nordisk"),
    (re.compile("ЭЛИ\\s+ЛИЛЛИ|LILLY", re.IGNORECASE), "Eli Lilly"),
    (re.compile("БРИСТОЛ-?МАЙЕРС\\s+СКВИББ|BRISTOL", re.IGNORECASE), "Bristol-Myers Squibb"),
    (re.compile("РОШ|ROCHE|ГЕНЕНТЕК|GENENTECH", re.IGNORECASE), "Roche"),
    (re.compile("ДЖОНСОН\\s+(И|&)\\s+ДЖОНСОН|JOHNSON\\s*&\\s*JOHNSON", re.IGNORECASE), "Johnson & Johnson"),
    (re.compile("АСТЕЛЛАС|ASTELLAS", re.IGNORECASE), "Astellas"),
    (re.compile("БОШ\\s+ЛОМБ|BAUSCH\\s+(\\+|&)\\s+LOMB", re.IGNORECASE), "Bausch & Lomb"),
    (re.compile("ЭББВИ|ABBVIE", re.IGNORECASE), "AbbVie"),
    (re.compile("АЛЛЕРГАН|ALLERGAN", re.IGNORECASE), "Allergan"),
    (re.compile("АМДЖЕН|AMGEN", re.IGNORECASE), "Amgen"),
    (re.compile("БОФУР\\s+ИПСЕН|БЕАУФОР|IPSEN", re.IGNORECASE), "Ipsen"),
    (re.compile("СЕЛДЖЕН|CELGENE", re.IGNORECASE), "Celgene"),
    (re.compile("ГИЛИАД|GILEAD", re.IGNORECASE), "Gilead"),
    (re.compile("ВИАТРИС|VIATRIS|МАЙЛАН|MYLAN", re.IGNORECASE), "Viatris"),
    (re.compile("АСПЕН|ASPEN", re.IGNORECASE), "Aspen"),
    (re.compile("УОРНЕР\\s+ЧИЛКОТТ|WARNER", re.IGNORECASE), "Warner Chilcott"),
    (re.compile("ХЕМОФАРМ|HEMOFARM", re.IGNORECASE), "Hemofarm"),
    (re.compile("ШРЕЯ\\s+ЛАЙФ", re.IGNORECASE), "Shreya Life Sciences"),
    (re.compile("ДЖОДАС\\s+ЭКСПОИМ", re.IGNORECASE), "Jodas Expoim"),
    (re.compile("САН\\s+ФАРМАСЬЮТИКАЛ|SUN\\s+PHARMA", re.IGNORECASE), "Sun Pharma"),
    (re.compile("ИПКА\\s+ЛАБОРАТОРИЗ|IPCA", re.IGNORECASE), "Ipca"),
    (re.compile("НОБЕЛ\\s+ИЛАЧ|NOBEL", re.IGNORECASE), "Nobel İlaç"),
    (re.compile("СЕНТИСС\\s+ФАРМА|SENTISS", re.IGNORECASE), "Sentiss"),
    (re.compile("ЗИГФРИД\\s+БАРБЕРА|SIEGFRIED", re.IGNORECASE), "Siegfried"),
    (re.compile("УОРЛД\\s+МЕДИЦИН", re.IGNORECASE), "World Medicine"),
    (re.compile("ФАРМАТЕН|PHARMATHEN", re.IGNORECASE), "Pharmathen"),
    (re.compile("ОКТАФАРМА|OCTAPHARMA", re.IGNORECASE), "Octapharma"),
    (re.compile("ОНКОМЕД|ONCOMED", re.IGNORECASE), "OncoMed"),
    (re.compile("АЛКАЛОИД|ALKALOID", re.IGNORECASE), "Alkaloid"),
    (re.compile("ПОЛЬФА|POLPHARMA", re.IGNORECASE), "Polpharma"),
    (re.compile("КОН-ФАРМА|KONPHARMA", re.IGNORECASE), "Кон-Фарма"),
    (re.compile("А\\.\\s*МЕНАРИНИ|MENARINI", re.IGNORECASE), "Menarini"),
    (re.compile("ДОКТОР\\s+ВИЛЬМАР\\s+ШВАБЕ|SCHWABE", re.IGNORECASE), "Dr. Willmar Schwabe"),
    (re.compile("НАТТЕРМАНН|NATTERMANN", re.IGNORECASE), "Nattermann"),
    (re.compile("РЕКОРДАТИ|RECORDATI", re.IGNORECASE), "Recordati"),
    (re.compile("ПАТЕОН|PATHEON", re.IGNORECASE), "Patheon"),
    (re.compile("ПРОТЕКХ\\s+БИОСИСТЕМС", re.IGNORECASE), "Protech Biosystems"),
    (re.compile("ОКСФОРД\\s+ЛАБОРАТОРИЗ", re.IGNORECASE), "Oxford Laboratories"),
    (re.compile("СИМПЕКС\\s+ФАРМА", re.IGNORECASE), "Simpex Pharma"),
    (re.compile("ХАЙГЛАНС", re.IGNORECASE), "Highglance Laboratories"),
    (re.compile("НАБРОС\\s+ФАРМА", re.IGNORECASE), "Nabros Pharma"),
    (re.compile("НОВАЛЕК", re.IGNORECASE), "Novalek"),
    (re.compile("ЛОК-БЕТА", re.IGNORECASE), "Lok-Beta"),
    (re.compile("М\\.?\\s*ДЖ\\.?\\s*БИОФАРМ", re.IGNORECASE), "M.J. Biopharm"),
    (re.compile("САНОВЕЛЬ|SANOVEL", re.IGNORECASE), "Sanovel"),
    (re.compile("КАРНАТАКА\\s+АНТИБИОТИКС", re.IGNORECASE), "Karnataka Antibiotics"),
    (re.compile("АЙПИЭР", re.IGNORECASE), "IPER Pharmaceutical"),
    (re.compile("ДАНАФА", re.IGNORECASE), "Danapha"),
    (re.compile("РЕЙОНГ", re.IGNORECASE), "Rayong Pharmaceutical"),
    (re.compile("СИНТОН", re.IGNORECASE), "Synthon"),
    (re.compile("ОРГАНОН|ORGANON", re.IGNORECASE), "Organon"),
    (re.compile("ФАМАР|FAMAR", re.IGNORECASE), "Famar"),
    (re.compile("ЭЙЧ\\s+БИ\\s+ЭМ\\s+ФАРМА", re.IGNORECASE), "HBM Pharma"),
    (re.compile("ФАРМЗАВОД\\s+ЕЛЬФА", re.IGNORECASE), "Farmzavod Elfa"),
    (re.compile("ПРО\\.?\\s*МЕД\\.?\\s*ЦС", re.IGNORECASE), "Pro.Med.CS Praha"),
    (re.compile("ЭКСЕЛЛА", re.IGNORECASE), "Excella"),
    (re.compile("ТАРХОМИНСКИЙ.*ПОЛЬФА", re.IGNORECASE), "Polfa Tarchomin"),
    (re.compile("ВАРШАВСКИЙ.*ПОЛЬФА", re.IGNORECASE), "Polfa Warszawa"),
    (re.compile("ДЕЛЬФАРМ|DELPHARM", re.IGNORECASE), "Delpharm"),
    (re.compile("КЛАБ\\s+ХАРКАНИ|HUNGARO|EGIS", re.IGNORECASE), "Egis"),
    (re.compile("ПОЛИФАРМ\\s+ИНДАСТРИЗ", re.IGNORECASE), "Polyfarm"),
    (re.compile("ФГБУ.*БЛОХИНА", re.IGNORECASE), "НМИЦ онкологии Блохина"),
    (re.compile("ФГБУ.*ЧУМАКОВА", re.IGNORECASE), "ФНЦИРИП Чумакова"),
    (re.compile("ФГБУ.*ГАМАЛЕИ|МЕДГАМАЛ", re.IGNORECASE), "НИЦЭМ Гамалеи"),
    (re.compile("НАЦИОНАЛЬНЫЙ\\s+МЕДИЦИНСКИЙ.*КАРДИОЛОГИИ", re.IGNORECASE), "НМИЦ кардиологии"),
    (re.compile("НИИ\\s+ВАКЦИН\\s+И\\s+СЫВОРОТОК", re.IGNORECASE), "НИИ вакцин и сывороток"),
    (re.compile("БЕЛМЕДПРЕПАРАТЫ", re.IGNORECASE), "Белмедпрепараты"),
    (re.compile("МИНСКИНТЕРКАПС", re.IGNORECASE), "Минскинтеркапс"),
    (re.compile("БОРИСОВСКИЙ.*МЕДИЦИНСКИХ", re.IGNORECASE), "Борисовский ЗМП"),
    (re.compile("БАРНАУЛЬСКИЙ.*МЕДИЦИНСКИХ", re.IGNORECASE), "Барнаульский ЗМП"),
    (re.compile("ИССЛЕДОВАТЕЛЬСКИЙ\\s+ИНСТИТУТ\\s+ХИМИЧЕСКОГО\\s+РАЗНООБРАЗИЯ", re.IGNORECASE), "ИИХР"),
    (re.compile("ХИМИКО-ФАРМАЦЕВТИЧЕСКИЙ\\s+ЗАВОД", re.IGNORECASE), "Химфармзавод"),
    (re.compile("ИНСТИТУТ\\s+БИООРГАНИЧЕСКОЙ\\s+ХИМИИ", re.IGNORECASE), "Институт биоорг. химии НАНБ"),
    (re.compile("ОБНИНСКАЯ\\s+ХИМИКО-ФАРМАЦЕВТИЧЕСКАЯ", re.IGNORECASE), "Обнинская ХФК"),
    (re.compile("ОМУТНИНСКАЯ.*ОПЫТНО-ПРОМЫШЛЕННАЯ", re.IGNORECASE), "Омутнинская НОПБ"),
    (re.compile("КЕМЕРОВСКАЯ\\s+ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА", re.IGNORECASE), "Кемеровская ФФ"),
    (re.compile("ЯРОСЛАВСКАЯ\\s+ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА", re.IGNORECASE), "Ярославская ФФ"),
    (re.compile("ТУЛЬСКАЯ\\s+ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА", re.IGNORECASE), "Тульская ФФ"),
    (re.compile("ЕРЕВАНСКАЯ\\s+ХИМИКО-ФАРМАЦЕВТИЧЕСКАЯ", re.IGNORECASE), "Ереванская ХФФ"),
    (re.compile("ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА\\s+САНКТ-ПЕТЕРБУРГА", re.IGNORECASE), "Санкт-Петербургская ФФ"),
    (re.compile("ГОМЕОПАТИЧЕСКИЙ\\s+МЕДИКО-СОЦИАЛЬНЫЙ", re.IGNORECASE), "Гомеопатический центр"),
    (re.compile("ХОЛДИНГ\\s+ЭДАС", re.IGNORECASE), "ЭДАС"),
    (re.compile("ФАРММЕНТАЛ", re.IGNORECASE), "Фармментал"),
    (re.compile("АЛИУМ", re.IGNORECASE), "Алиум"),
    (re.compile("НПФ\\s+МАТЕРИА\\s+МЕДИКА", re.IGNORECASE), "Materia Medica"),
    (re.compile("ХИНОИН", re.IGNORECASE), "Chinoin"),
    (re.compile("ОАО\\s+НЕСВИЖСКИЙ.*МЕДИЦИНСКИХ", re.IGNORECASE), "Несвижский ЗМП"),
    (re.compile("ФАРМАСЬЮТИКАЛ\\s+МАНУФЭКЧУРИНГ\\s+РИСЕРЧ", re.IGNORECASE), "Pharmaceutical Manufacturing Research"),
    (re.compile("ДР\\.?\\s*ГЕРХАРД\\s+МАНН|DR\\.?\\s*MANN", re.IGNORECASE), "Dr. Mann Pharma"),
    (re.compile("АМВ\\s+ГМБХ.*ВАРНГАУ", re.IGNORECASE), "AMW Arzneimittelwerk"),
    (re.compile("РОМФАРМ\\s+ИЛАЧ|ROMPHARM", re.IGNORECASE), "Rompharm"),
    (re.compile("ХАСКО-ЛЕК|HASCO-LEK", re.IGNORECASE), "Hasco-Lek"),
    (re.compile("КЬЕЗИ|CHIESI", re.IGNORECASE), "Chiesi"),
    (re.compile("УНИ-ФАРМА\\s+КЛЕОН|UNI-PHARMA", re.IGNORECASE), "Uni-Pharma"),
    (re.compile("ГЛЕНМЕРИ\\s+БИОТЕХНОЛОДЖИС|GLENMERY", re.IGNORECASE), "Glenmery Biotech"),
    (re.compile("АЛЕКСАНДРИЯ\\s+ХИМИКО|ХИМИКО.*АЛЕКСАНДРИЯ", re.IGNORECASE), "Alexandria CPI"),
    (re.compile("НОРТ\\s+ЧАЙНА\\s+ФАРМАСЬЮТИКАЛ|NORTH\\s+CHINA\\s+PHARMACEUTICAL", re.IGNORECASE), "NCPC"),
    (re.compile("АВАРА\\s+ЛИСКАТЕ", re.IGNORECASE), "Avara Liscate"),
    (re.compile("МАИНЛУН|MAINLUNG", re.IGNORECASE), "Mainlung Pharmaceutical"),
    (re.compile("ХЕННИГ\\s+АРЦНАЙМИТТЕЛЬ|HENNIG", re.IGNORECASE), "Hennig Arzneimittel"),
    (re.compile("ФУДЗИ\\s+ЯКУХИН|FUJI\\s+YAKUHIN", re.IGNORECASE), "Fuji Yakuhin"),
    (re.compile("ТРОММСДОРФФ|TROMMSDORFF", re.IGNORECASE), "Trommsdorff"),
    (re.compile("ЛЕМЕРИ|LEMERY", re.IGNORECASE), "Lemery"),
    (re.compile("ЛИОФИЛИЗЕЙШН\\s+СЕРВИСЕЗ", re.IGNORECASE), "Lyophilization Services"),
    (re.compile("ХАНЧЖОУ\\s+ЧЖУНМЭЙ\\s+ХУАДУН|HANGZHOU", re.IGNORECASE), "Hangzhou Zhongmei Huadong"),
    (re.compile("МОСХИМФАРМПРЕПАРАТЫ|МХФП", re.IGNORECASE), "Мосхимфармпрепараты"),
    (re.compile("РНПЦ\\s+ТРАНСФУЗИОЛОГИИ", re.IGNORECASE), "РНПЦ трансфузиологии"),
    (re.compile("НМИЦК.*ЧАЗОВА|КАРДИОЛОГИИ.*ЧАЗОВА", re.IGNORECASE), "НМИЦ кардиологии Чазова"),
    (re.compile("ПРОТИВОЧУМНЫЙ\\s+ИНСТИТУТ\\s+МИКРОБ", re.IGNORECASE), "НИПЧИ Микроб"),
    (re.compile("КАРАГАНДИНСКИЙ\\s+ФАРМАЦЕВТИЧЕСКИЙ", re.IGNORECASE), "Карагандинский ФК"),
    (re.compile("ЦЕНТР\\s+ГЕННОЙ\\s+ИНЖЕНЕРИИ", re.IGNORECASE), "Центр генной инженерии"),
    (re.compile("ШУГАИ\\s+ФАРМА|CHUGAI", re.IGNORECASE), "Chugai Pharma"),
    (re.compile("МОНТАВИТ|MONTAVIT", re.IGNORECASE), "Montavit"),
    (re.compile("МИКРОХИМ(?![А-Я])", re.IGNORECASE), "Микрохим"),
    (re.compile("ТВЕРЬГАЗСЕРВИС", re.IGNORECASE), "Тверьгазсервис"),
    (re.compile("ВЕРВАГ\\s+ФАРМА|WORWAG", re.IGNORECASE), "Wörwag Pharma"),
    (re.compile("ЭБЕВЕ\\s+ФАРМА|EBEWE", re.IGNORECASE), "Ebewe Pharma"),
    (re.compile("ЭЙСАЙ|EISAI", re.IGNORECASE), "Eisai"),
    (re.compile("АНЖЕЛИНИ|ANGELINI|ACRAF", re.IGNORECASE), "Angelini"),
    (re.compile("ПОЛЬ-БОСКАМП|POHL-BOSKAMP|G\\.\\s*POHL", re.IGNORECASE), "Pohl-Boskamp"),
    (re.compile("ДЕНТИНОКС|DENTINOX", re.IGNORECASE), "Dentinox"),
    (re.compile("ВАЙЕТ|WYETH", re.IGNORECASE), "Wyeth"),
    (re.compile("ВЕТТЕР-ФАРМА|VETTER", re.IGNORECASE), "Vetter Pharma"),
    (re.compile("АРТЕЗАН", re.IGNORECASE), "Artesan"),
    (re.compile("АТЛАНТИК\\s+ФАРМА", re.IGNORECASE), "Atlantic Pharma"),
    (re.compile("РОНТИС", re.IGNORECASE), "Rontis"),
    (re.compile("ЛИХТЕНХЕЛЬДТ", re.IGNORECASE), "Lichtenheldt"),
    (re.compile("ГЛОБОФАРМ", re.IGNORECASE), "Globopharm"),
    (re.compile("ДОЛОРГИТ", re.IGNORECASE), "Dolorgiet"),
    (re.compile("САНУМ-КЕЛЬБЕК", re.IGNORECASE), "Sanum-Kehlbeck"),
    (re.compile("МЕРЦ\\s+ФАРМА|MERZ\\s+PHARMA", re.IGNORECASE), "Merz Pharma"),
    (re.compile("ЭНГЕЛЬХАРД\\s+АРЦНАЙМИТТЕЛЬ|ENGELHARD", re.IGNORECASE), "Engelhard Arzneimittel"),
    (re.compile("АЛЕКСИОН|ALEXION", re.IGNORECASE), "Alexion"),
    (re.compile("ФЕРРИНГ|FERRING", re.IGNORECASE), "Ferring"),
    (re.compile("АЙВЭКС", re.IGNORECASE), "Ivax"),
    (re.compile("НОРТОН\\s+ВОТЕРФОРД", re.IGNORECASE), "Norton Waterford"),
    (re.compile("ПИ\\s+ЭНД\\s+ДЖИ\\s+ХЭЛС|P&G\\s+HEALTH", re.IGNORECASE), "P&G Health"),
    (re.compile("Ц\\.?П\\.?М\\.?\\s+КОНТРАКТФАРМА|КОНТРАКТФАРМА", re.IGNORECASE), "CPM Contractpharma"),
    (re.compile("ДЖНТЛ\\s+КОНСЬЮМЕР", re.IGNORECASE), "JNTL Consumer Health"),
    (re.compile("МСД\\s+ИНТЕРНЕЙШНЛ|MERCK\\s+SHARP", re.IGNORECASE), "MSD"),
    (re.compile("ПОЛИСАН|POLYSAN", re.IGNORECASE), "Polysan"),
    (re.compile("ЭСКОМ(?![А-Я])", re.IGNORECASE), "ЭСКОМ"),
    (re.compile("НОБЕЛ\\s+АЛМАТИНСКАЯ", re.IGNORECASE), "Nobel Алматы"),
    (re.compile("ГЕНВЕОН", re.IGNORECASE), "Genveon"),
    (re.compile("АЗИЕНДЕ\\s+КИМИКЕ", re.IGNORECASE), "Angelini ACRAF"),
    (re.compile("ЛУЗОМЕДИКАМЕНТА", re.IGNORECASE), "Lusomedicamenta"),
    (re.compile("АПОТЭК\\s+ПРОДУКЦИОН", re.IGNORECASE), "Apotek Produktion"),
    (re.compile("ЛАБОРАТОРИОС\\s+МЕДИКАМЕНТОС", re.IGNORECASE), "Laboratorios Medicamentos"),
    (re.compile("ОМАН\\s+ФАРМАСЬЮТИКАЛ", re.IGNORECASE), "Oman Pharmaceutical"),
    (re.compile("АРМАВИРСКАЯ.*АПТЕЧНАЯ", re.IGNORECASE), "Армавирская АПТ-база"),
    (re.compile("ГАЛЕНИКА|GALENIKA", re.IGNORECASE), "Galenika"),
    (re.compile("НАУЧНО-ТЕХНОЛОГИЧЕСКАЯ.*ПОЛИСАН", re.IGNORECASE), "Polysan"),
    (re.compile("СИБИРСКИЙ\\s+ЦЕНТР\\s+ФАРМАКОЛОГИИ", re.IGNORECASE), "Сибирский ЦФБ"),
    (re.compile("НПК\\s+ЭСКОМ|КОНЦЕРН\\s+ЭСКОМ", re.IGNORECASE), "ЭСКОМ"),
    (re.compile("ЕГИПЕТСКАЯ\\s+МЕЖДУНАРОДНАЯ", re.IGNORECASE), "Egyptian Int. Pharma"),
    (re.compile("СЕВЕРНАЯ\\s+КИТАЙСКАЯ", re.IGNORECASE), "NCPC"),
    (re.compile("СЫЧУАНЬСКАЯ", re.IGNORECASE), "Sichuan Yuanda"),
    (re.compile("ХЭБЭЙ\\s+ХУАМИНЬ", re.IGNORECASE), "Hebei Huamin"),
    (re.compile("ХИНОИН", re.IGNORECASE), "Chinoin"),
    (re.compile("НОВЕЛЛ\\s+ФАРМАСЬЮТИКАЛ", re.IGNORECASE), "Novell Pharma"),
    (re.compile("МЕКОФАР", re.IGNORECASE), "Mekophar"),
    (re.compile("ДОДЖИН\\s+ИЯКУ-КАКО", re.IGNORECASE), "Dojin Iyaku-Kako"),
    (re.compile("ФАРМАЦЕВТИЧЕСКАЯ\\s+КОМПАНИЯ\\s+АЛИУМ|АЛИУМ(?![А-Я])", re.IGNORECASE), "Алиум"),
    (re.compile("НАУЧНО-ПРОИЗВОДСТВЕННЫЙ\\s+КОНЦЕРН\\s+ПОЛИСАН|КОНЦЕРН\\s+ПОЛИСАН", re.IGNORECASE), "Polysan"),
    (re.compile("ОБНИНСКАЯ\\s+ХИМИКО-ФАРМАЦЕВТИЧЕСКАЯ", re.IGNORECASE), "Обнинская ХФК"),
    (re.compile("ТЮМЕНСКИЙ\\s+ХИМИКО-ФАРМАЦЕВТИЧЕСКИЙ", re.IGNORECASE), "Тюменский ХФЗ"),
    (re.compile("ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА\\s+САНКТ-ПЕТЕРБУРГА", re.IGNORECASE), "Санкт-Петербургская ФФ"),
    (re.compile("ФГАНУ\\s+ФНЦИРИП|ФНЦИРИП", re.IGNORECASE), "ФНЦИРИП"),
    (re.compile("ФКУЗ\\s+РОСНИПЧИ\\s+МИКРОБ", re.IGNORECASE), "НИПЧИ Микроб"),
    (re.compile("ФКУЗ\\s+СТАВРОПОЛЬСКИЙ\\s+ПРОТИВОЧУМНЫЙ", re.IGNORECASE), "Ставропольский ПЧИ"),
    (re.compile("ФБУ\\s+НАУКИ\\s+РОСТОВСКИЙ\\s+НИИ", re.IGNORECASE), "Ростовский НИИ микробиологии"),
    (re.compile("ФГАОУ?\\s*О?У?\\s*ВО?\\s+РОССИЙСКИЙ\\s+УНИВЕРСИТЕТ\\s+ДРУЖБЫ", re.IGNORECASE), "РУДН"),
    (re.compile("ФГБУ\\s+48.*НИИ\\s+МИНИСТЕРСТВА\\s+ОБОРОНЫ", re.IGNORECASE), "48 ЦНИИ МО РФ"),
    (re.compile("НИЦ\\s+48\\s+ЦНИИ\\s+МИНИСТЕРСТВА", re.IGNORECASE), "48 ЦНИИ МО РФ"),
    (re.compile("ВАЙЕТ\\s+ФАРМАСЬЮТИКАЛЗ.*ВАЙЕТ\\s+ХОЛДИНГЗ", re.IGNORECASE), "Wyeth"),
    (re.compile("ЛИЛЛИ\\s+ДЕЛЬ\\s+КАРИБЕ", re.IGNORECASE), "Eli Lilly del Caribe"),
    (re.compile("ВОЛОГОДСК.*СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ", re.IGNORECASE), "Вологодская ОСПК"),
    (re.compile("ИВАНОВСК.*СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ", re.IGNORECASE), "Ивановская ОСПК"),
    (re.compile("САМАРСК.*СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ", re.IGNORECASE), "Самарская ОСПК"),
    (re.compile("ТАМБОВСК.*СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ", re.IGNORECASE), "Тамбовская ОСПК"),
    (re.compile("ТЮМЕНСК.*СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ", re.IGNORECASE), "Тюменская ОСПК"),
    (re.compile("НИЖЕГОРОДСК.*ЦЕНТР\\s+КРОВИ", re.IGNORECASE), "Нижегородский ОЦК"),
    (re.compile("НПК\\s+МЗ\\s+РФ", re.IGNORECASE), "Российский кардио-НПК"),
    (re.compile("ОБЛАСТНАЯ\\s+СТАНЦИЯ\\s+ПЕРЕЛИВАНИЯ\\s+КРОВИ", re.IGNORECASE), "ОСПК"),
    (re.compile("АО\\s+КЕМЕРОВСКАЯ\\s+ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА", re.IGNORECASE), "Кемеровская ФФ"),
    (re.compile("ОАО\\s+КЕМЕРОВСКАЯ\\s+ФАРМАЦЕВТИЧЕСКАЯ\\s+ФАБРИКА", re.IGNORECASE), "Кемеровская ФФ"),
    (re.compile("ДОКТОР\\s+ГУСТАВ\\s+КЛЯЙН", re.IGNORECASE), "Dr. Gustav Klein"),
    (re.compile("ХАБЭЙ\\s+ХУАМИНЬ", re.IGNORECASE), "Hebei Huamin"),
    (re.compile("Г\\.\\s*ПОЛЬ-БОСКАМП", re.IGNORECASE), "G. Pohl-Boskamp"),
]


def _is_all_caps(s: str) -> bool:
    if not s or not isinstance(s, str):
        return False
    letters = [c for c in s if c.isalpha()]
    if len(letters) < 3:
        return False
    upper = [c for c in letters if c == c.upper() and c != c.lower()]
    return (len(upper) / len(letters)) >= 0.85


def _title_word(w: str) -> str:
    if not w or not any(c.isalpha() for c in w):
        return w
    KEEP_ABBR = {"ХФЗ", "НПО", "АХФ", "ХФК", "РФ", "МНН", "ЦМТ",
                 "РУС", "НПП", "НПК", "СНГ", "СПБ"}
    if w == w.upper() and all('А' <= c <= 'я' or c == 'Ё' or c == 'ё' for c in w if c.isalpha()):
        # All-caps cyrillic with no vowels — likely abbreviation
        vowels = set("АЕЁИОУЫЭЮЯаеёиоуыэюя")
        if not any(c in vowels for c in w):
            return w
    if w in KEEP_ABBR:
        return w
    return w[0].upper() + w[1:].lower()


def format_manufacturer(s):
    """Return brand-cased manufacturer name for display (Yandex/Google sniff).

    Pass-through for empty/None. Does NOT mutate the DB value.
    """
    if not s or not isinstance(s, str):
        return s
    trimmed = s.strip().replace("«", "").replace("»", "").replace('"', '')

    # 1. Brand-override fast-path
    for pat, brand in BRAND_OVERRIDES:
        if pat.search(trimmed):
            return brand

    v = trimmed
    # 2. Strip leading legal forms iteratively
    changed = True
    while changed:
        changed = False
        for lf in LEGAL_FORMS:
            esc = re.escape(lf)
            m = re.match(rf"^{esc}(?=\s|[.,]|$)[\s.,]*", v, re.IGNORECASE)
            if m:
                v = v[m.end():]
                changed = True

    # 3. Strip trailing leading-style legal form ("ГЕДЕОН РИХТЕР ОАО")
    for lf in LEGAL_FORMS:
        v = re.sub(rf"[\s,]+{re.escape(lf)}\s*$", "", v, flags=re.IGNORECASE)

    # 4. Cut at first comma if tail contains a foreign legal token
    comma_idx = v.find(",")
    if comma_idx > 0:
        tail = v[comma_idx + 1:].upper()
        tail_has_legal = any(
            re.search(rf"(^|[\s,.]){re.escape(tok)}(?=$|[\s,.])", tail)
            for tok in FOREIGN_LEGAL_TOKENS
        )
        if tail_has_legal:
            v = v[:comma_idx]

    # 5. Iteratively strip trailing legal-form tokens (handles chains
    #    like "ПВТ. ЛТД.", "ГМБХ И КО. КГ", "Ко.ЛТД").
    prev = ""
    iters = 0
    while prev != v and iters < 10:
        prev = v
        iters += 1
        # glue patterns
        v = re.sub(r"[\s,]+(?:И|AND|ЭНД|&)\s*КО\.?\s*(?:КГ|ОГ|ЛТД|LTD|KG|OG)?\s*$", "", v, flags=re.IGNORECASE).strip()
        v = re.sub(r"[\s,.]+КО\.?\s*(?:ЛТД|LTD|КГ|KG|ОГ|OG|КГАА|KGAA)\s*$", "", v, flags=re.IGNORECASE).strip()
        v = re.sub(r"[\s,]+КО\.?\s*$", "", v, flags=re.IGNORECASE).strip()
        # orphan connector
        v = re.sub(r"[\s,]+(?:И|AND|ЭНД|&)\s*$", "", v, flags=re.IGNORECASE).strip()
        for tok in SAFE_TRAIL:
            v = re.sub(rf"[\s,.]+{re.escape(tok)}\s*$", "", v, flags=re.IGNORECASE)

    # 6. Trim leftover punctuation
    v = re.sub(r"[\s.,;:]+$", "", v.strip())
    v = re.sub(r"^[,\s]+", "", v)
    if not v:
        return s

    # 7. Title-case only if input was all-caps
    if not _is_all_caps(s):
        return v
    return "".join(_title_word(w) for w in re.split(r"(\s+|[-/])", v))


def manufacturer_brand_and_legal(s):
    """Return (brand_name, legal_name) tuple for schema.org manufacturer.

    brand_name: human-friendly short brand (e.g. "KRKA")
    legal_name: original raw juridical name (e.g. "АО КРКА, Д.Д., НОВО МЕСТО")
    """
    if not s:
        return (None, None)
    return (format_manufacturer(s), s.strip())

