"""Apply the October user-approved identity corrections with a recoverable snapshot.

Run preview first. The generic Azathioprine URL is retained, but its foreign
pack identifiers, offers and manufacturer metadata must not cross to Russia.
"""
import argparse
import os
import subprocess
import sys
from datetime import datetime, timezone
from uuid import uuid4

from dotenv import load_dotenv
from pymongo import MongoClient
from scripts.import_priority_medications import ROOT, SOURCE


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    load_dotenv(ROOT / ".env")
    db = MongoClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]
    docs = list(db.medications.find({"curated_source": SOURCE}))
    az = next(d for d in docs if d["slug"] == "azatioprin-50-mg-tabletki")
    if az["manufacturer"] not in ("TILLOMED", "МОСХИМФАРМПРЕПАРАТЫ ИМ. Н. А. СЕМАШКО"):
        raise ValueError("Unexpected Azathioprine identity; refusing replacement")
    if not args.apply:
        subprocess.run([sys.executable, "-m", "scripts.import_priority_medications"], check=True)
        print("PREVIEW: snapshot curated cards/prices; replace foreign Azathioprine; remove Isentress №50 reference")
        return
    batch = "catalog-corrections-2026-10-" + uuid4().hex
    slugs = [d["slug"] for d in docs]
    for collection, query in (
        ("medications", {"curated_source": SOURCE}),
        ("prices", {"slug": {"$in": slugs}}),
        ("prices_real", {"slug": {"$in": slugs}}),
    ):
        for doc in db[collection].find(query):
            db.curated_import_backups.insert_one({
                "batch_id": batch, "collection": collection,
                "action": "october-identity-snapshot", "document": doc,
                "backed_up_at": datetime.now(timezone.utc),
            })
    subprocess.run([sys.executable, "-m", "scripts.import_priority_medications", "--apply", "--prune"], check=True)
    if az["manufacturer"] == "TILLOMED":
        identity = {"$or": [{"slug": az["slug"]}, {"medication_id": az["_id"]}, {"medication_id": str(az["_id"])}]}
        for collection in ("prices", "prices_real"):
            db[collection].delete_many(identity)
        db.medications.update_one({"_id": az["_id"]}, {"$unset": {"manufacturer_official": "", "image_url": ""}})
    db.prices_real.delete_many({
        "slug": "isentress-400-mg-tabletki-pokrytye-obolochkoy",
        "archive_observation": True, "gz_pack": "50 шт",
    })
    # Re-key only identifiers generated by our curated importer, not registry GTINs.
    for doc in db.medications.find({"curated_source": SOURCE}):
        variants = doc.get("variants") or []
        for index, variant in enumerate(variants, 1):
            if "curated_variant_id" in variant:
                variant["curated_variant_id"] = f"{doc['curated_key']}:{index}"
        db.medications.update_one({"_id": doc["_id"]}, {"$set": {"variants": variants}})
    for module in ("scripts.import_priority_network_price_archive", "scripts.apply_priority_medication_seo"):
        subprocess.run([sys.executable, "-m", module, "--apply"], check=True)
    print("Snapshot batch:", batch)


if __name__ == "__main__":
    main()
