#!/usr/bin/env node
// Extract BRAND_OVERRIDES + FOREIGN_LEGAL_TOKENS + LEGAL_FORMS from text.mjs
// and emit a Python module with equivalent regexes and the same logic.

import * as text from './text.mjs';
import { readFileSync } from 'fs';

// We re-parse text.mjs to extract the constants (they're not exported).
const src = readFileSync('./text.mjs', 'utf8');

function extractArr(name) {
  // matches `const NAME = [ ... ];` (multi-line)
  const re = new RegExp(`const\\s+${name}\\s*=\\s*\\[([\\s\\S]*?)\\];`);
  const m = src.match(re);
  return m ? m[1] : '';
}

const LEGAL = extractArr('LEGAL_FORMS');
const FOREIGN = extractArr('FOREIGN_LEGAL_TOKENS');
const OVERRIDES = extractArr('BRAND_OVERRIDES');

// Parse comma-separated quoted strings out of an array body.
function parseStrings(body) {
  const out = [];
  const re = /'([^']*)'/g;
  let m;
  while ((m = re.exec(body))) out.push(m[1]);
  return out;
}

// Parse [/regex/i, 'Brand'] pairs from OVERRIDES.
function parseOverrides(body) {
  // greedy match — each pair `[/RE/flags, 'Brand'],`
  const re = /\[\s*\/((?:\\\/|[^\/])+)\/([gimuy]*)\s*,\s*'((?:\\'|[^'])*)'\s*\]/g;
  const out = [];
  let m;
  while ((m = re.exec(body))) {
    const [, pat, flags, brand] = m;
    out.push({ pat, flags, brand });
  }
  return out;
}

const legalForms = parseStrings(LEGAL);
const foreignTokens = parseStrings(FOREIGN);
const overrides = parseOverrides(OVERRIDES);

console.error('Parsed:', legalForms.length, 'legal forms,',
  foreignTokens.length, 'foreign tokens,', overrides.length, 'overrides');

// Emit Python module
const py = `"""Manufacturer name normalisation for SSR/SEO output.

Mirrors frontend/src/utils/text.js \`formatManufacturer\`.
Strips juridical-form prefixes/suffixes and replaces known long names
with canonical brand names (e.g. "АО КРКА, Д.Д., НОВО МЕСТО" → "KRKA").

AUTOGENERATED — do not edit. Source: frontend/src/utils/text.js.
Regenerate by running: node /app/gen_python_port.mjs > backend/api/text_format.py
"""
import re
import unicodedata

LEGAL_FORMS = [
${legalForms.map(s => '    ' + JSON.stringify(s)).join(',\n')},
]

FOREIGN_LEGAL_TOKENS = [
${foreignTokens.map(s => '    ' + JSON.stringify(s)).join(',\n')},
]

# Tokens that are SAFE to strip even if they are the last word.
# Excludes PHARMA/HEALTHCARE/LABORATORIES/INDUSTRIES/HOLDING/GROUP/INTERNATIONAL
# (they are often part of the brand itself, e.g. "Sun Pharma").
_UNSAFE_TRAIL_RE = re.compile(
    r"(PHARMA|HEALTHCARE|LABORATOR|INDUSTR|HOLDING|GROUP|TRADING|INTERNATIONAL"
    r"|КОМПАНИ|ИНДАСТРИЗ|ЛАБОРАТОРИ|ИНТЕРНЕШНЛ|ХОЛДИНГ|ГРУПП|ХЕЛСК"
    r"|COMPANY|COMPAGNIE|ARZNEIMITTEL|PHARMACEUTICAL)",
    re.IGNORECASE,
)
SAFE_TRAIL = [t for t in FOREIGN_LEGAL_TOKENS if not _UNSAFE_TRAIL_RE.search(t)]

# Order matters — more specific patterns first.
BRAND_OVERRIDES = [
${overrides.map(o => '    (re.compile(' + JSON.stringify(o.pat) + ', re.IGNORECASE), ' + JSON.stringify(o.brand) + ')').join(',\n')},
]


def _is_all_caps(s: str) -> bool:
    if not s or not isinstance(s, str):
        return False
    letters = [c for c in s if c.isalpha()]
    if len(letters) < 3:
        return False
    upper = [c for c in letters if c == c.upper() and c != c.lower()]
    return (len(upper) / len(letters)) >= 0.85


def _title_word(w: str) -> str:
    if not w or not any(c.isalpha() for c in w):
        return w
    KEEP_ABBR = {"ХФЗ", "НПО", "АХФ", "ХФК", "РФ", "МНН", "ЦМТ",
                 "РУС", "НПП", "НПК", "СНГ", "СПБ"}
    if w == w.upper() and all('А' <= c <= 'я' or c == 'Ё' or c == 'ё' for c in w if c.isalpha()):
        # All-caps cyrillic with no vowels — likely abbreviation
        vowels = set("АЕЁИОУЫЭЮЯаеёиоуыэюя")
        if not any(c in vowels for c in w):
            return w
    if w in KEEP_ABBR:
        return w
    return w[0].upper() + w[1:].lower()


def format_manufacturer(s):
    """Return brand-cased manufacturer name for display (Yandex/Google sniff).

    Pass-through for empty/None. Does NOT mutate the DB value.
    """
    if not s or not isinstance(s, str):
        return s
    trimmed = s.strip().replace("«", "").replace("»", "").replace('"', '')

    # 1. Brand-override fast-path
    for pat, brand in BRAND_OVERRIDES:
        if pat.search(trimmed):
            return brand

    v = trimmed
    # 2. Strip leading legal forms iteratively
    changed = True
    while changed:
        changed = False
        for lf in LEGAL_FORMS:
            esc = re.escape(lf)
            m = re.match(rf"^{esc}(?=\\s|[.,]|$)[\\s.,]*", v, re.IGNORECASE)
            if m:
                v = v[m.end():]
                changed = True

    # 3. Strip trailing leading-style legal form ("ГЕДЕОН РИХТЕР ОАО")
    for lf in LEGAL_FORMS:
        v = re.sub(rf"[\\s,]+{re.escape(lf)}\\s*$", "", v, flags=re.IGNORECASE)

    # 4. Cut at first comma if tail contains a foreign legal token
    comma_idx = v.find(",")
    if comma_idx > 0:
        tail = v[comma_idx + 1:].upper()
        tail_has_legal = any(
            re.search(rf"(^|[\\s,.]){re.escape(tok)}(?=$|[\\s,.])", tail)
            for tok in FOREIGN_LEGAL_TOKENS
        )
        if tail_has_legal:
            v = v[:comma_idx]

    # 5. Iteratively strip trailing legal-form tokens (handles chains
    #    like "ПВТ. ЛТД.", "ГМБХ И КО. КГ", "Ко.ЛТД").
    prev = ""
    iters = 0
    while prev != v and iters < 10:
        prev = v
        iters += 1
        # glue patterns
        v = re.sub(r"[\\s,]+(?:И|AND|ЭНД|&)\\s*КО\\.?\\s*(?:КГ|ОГ|ЛТД|LTD|KG|OG)?\\s*$", "", v, flags=re.IGNORECASE).strip()
        v = re.sub(r"[\\s,.]+КО\\.?\\s*(?:ЛТД|LTD|КГ|KG|ОГ|OG|КГАА|KGAA)\\s*$", "", v, flags=re.IGNORECASE).strip()
        v = re.sub(r"[\\s,]+КО\\.?\\s*$", "", v, flags=re.IGNORECASE).strip()
        # orphan connector
        v = re.sub(r"[\\s,]+(?:И|AND|ЭНД|&)\\s*$", "", v, flags=re.IGNORECASE).strip()
        for tok in SAFE_TRAIL:
            v = re.sub(rf"[\\s,.]+{re.escape(tok)}\\s*$", "", v, flags=re.IGNORECASE)

    # 6. Trim leftover punctuation
    v = re.sub(r"[\\s.,;:]+$", "", v.strip())
    v = re.sub(r"^[,\\s]+", "", v)
    if not v:
        return s

    # 7. Title-case only if input was all-caps
    if not _is_all_caps(s):
        return v
    return "".join(_title_word(w) for w in re.split(r"(\\s+|[-/])", v))


def manufacturer_brand_and_legal(s):
    """Return (brand_name, legal_name) tuple for schema.org manufacturer.

    brand_name: human-friendly short brand (e.g. "KRKA")
    legal_name: original raw juridical name (e.g. "АО КРКА, Д.Д., НОВО МЕСТО")
    """
    if not s:
        return (None, None)
    return (format_manufacturer(s), s.strip())
`;

console.log(py);
