// Mock data for аптечный агрегатор. Будет заменено реальным API на этапе бэкенда.

export const CATEGORIES = [
  { slug: 'ot-prostudy', title: 'От простуды и гриппа', icon: 'Thermometer', color: '#FEE2E2', accent: '#DC2626' },
  { slug: 'obezbolivayuschie', title: 'Обезболивающие', icon: 'Pill', color: '#FEF3C7', accent: '#D97706' },
  { slug: 'vitaminy-bady', title: 'Витамины и БАДы', icon: 'Leaf', color: '#DCFCE7', accent: '#16A34A' },
  { slug: 'zhkt', title: 'ЖКТ и пищеварение', icon: 'Apple', color: '#FFE4E6', accent: '#E11D48' },
  { slug: 'serdce', title: 'Сердце и сосуды', icon: 'HeartPulse', color: '#E0E7FF', accent: '#4F46E5' },
  { slug: 'allergiya', title: 'Аллергия', icon: 'Wind', color: '#CFFAFE', accent: '#0891B2' },
  { slug: 'antibiotiki', title: 'Антибиотики', icon: 'Shield', color: '#F3E8FF', accent: '#7E22CE' },
  { slug: 'mat-i-ditya', title: 'Мать и дитя', icon: 'Baby', color: '#FCE7F3', accent: '#DB2777' },
  { slug: 'glaza', title: 'Глаза', icon: 'Eye', color: '#DBEAFE', accent: '#1D4ED8' },
  { slug: 'kozha', title: 'Дерматология', icon: 'Sparkles', color: '#FEF9C3', accent: '#CA8A04' },
  { slug: 'gigiena', title: 'Гигиена и уход', icon: 'Droplets', color: '#E0F2FE', accent: '#0369A1' },
  { slug: 'nervnaya', title: 'Нервная система', icon: 'Brain', color: '#EDE9FE', accent: '#6D28D9' },
];

export const PHARMACIES = [
  // Москва
  { id: 'p1', city: 'msk', name: 'Аптека «Здоровье»', chain: 'Здоровье', address: 'Москва, ул. Тверская, 12', metro: 'Тверская', phone: '+7 (495) 123-45-67', hours: 'Пн–Вс: 08:00–22:00', lat: 55.7615, lng: 37.6063, rating: 4.7 },
  { id: 'p2', city: 'msk', name: 'Аптека «36,6»', chain: '36,6', address: 'Москва, Ленинградский пр-т, 39', metro: 'Динамо', phone: '+7 (495) 234-56-78', hours: 'Круглосуточно', lat: 55.7903, lng: 37.5546, rating: 4.5 },
  { id: 'p3', city: 'msk', name: 'Ригла', chain: 'Ригла', address: 'Москва, ул. Арбат, 28', metro: 'Арбатская', phone: '+7 (495) 345-67-89', hours: 'Пн–Вс: 09:00–23:00', lat: 55.7494, lng: 37.5934, rating: 4.6 },
  { id: 'p4', city: 'msk', name: 'Горздрав', chain: 'Горздрав', address: 'Москва, Кутузовский пр-т, 22', metro: 'Кутузовская', phone: '+7 (495) 456-78-90', hours: 'Пн–Вс: 07:00–23:00', lat: 55.7400, lng: 37.5505, rating: 4.4 },
  { id: 'p5', city: 'msk', name: 'Столички', chain: 'Столички', address: 'Москва, Профсоюзная, 56', metro: 'Новые Черёмушки', phone: '+7 (495) 567-89-01', hours: 'Круглосуточно', lat: 55.6790, lng: 37.5500, rating: 4.3 },
  { id: 'p6', city: 'msk', name: 'Аптека «Будь Здоров»', chain: 'Будь Здоров', address: 'Москва, ул. Мясницкая, 8', metro: 'Лубянка', phone: '+7 (495) 678-90-12', hours: 'Пн–Вс: 08:00–22:00', lat: 55.7616, lng: 37.6299, rating: 4.5 },
  { id: 'p7', city: 'msk', name: 'Самсон-Фарма', chain: 'Самсон-Фарма', address: 'Москва, Комсомольский пр-т, 14', metro: 'Парк культуры', phone: '+7 (495) 789-01-23', hours: 'Пн–Вс: 09:00–22:00', lat: 55.7274, lng: 37.5863, rating: 4.6 },
  { id: 'p8', city: 'msk', name: 'Аптеки А5', chain: 'А5', address: 'Москва, Большая Дмитровка, 32', metro: 'Чеховская', phone: '+7 (495) 890-12-34', hours: 'Пн–Вс: 08:00–23:00', lat: 55.7691, lng: 37.6149, rating: 4.4 },
  { id: 'p9', city: 'msk', name: 'Аптечная сеть «Ноль Боли»', chain: 'Ноль Боли', address: 'Москва, ул. Пятницкая, 25', metro: 'Третьяковская', phone: '+7 (495) 901-23-45', hours: 'Пн–Вс: 09:00–21:00', lat: 55.7398, lng: 37.6259, rating: 4.2 },
  { id: 'p10', city: 'msk', name: 'Доктор Столетов', chain: 'Доктор Столетов', address: 'Москва, Мичуринский пр-т, 31', metro: 'Раменки', phone: '+7 (495) 012-34-56', hours: 'Пн–Вс: 08:00–22:00', lat: 55.6951, lng: 37.5031, rating: 4.5 },
  { id: 'p11', city: 'msk', name: 'Аптека Wer.ru', chain: 'Wer.ru', address: 'Москва, ул. Новый Арбат, 15', metro: 'Арбатская', phone: '+7 (495) 111-22-33', hours: 'Круглосуточно', lat: 55.7522, lng: 37.5944, rating: 4.7 },
  { id: 'p12', city: 'msk', name: 'Планета Здоровья', chain: 'Планета Здоровья', address: 'Москва, Дмитровское ш., 71', metro: 'Селигерская', phone: '+7 (495) 222-33-44', hours: 'Пн–Вс: 08:00–22:00', lat: 55.8728, lng: 37.5468, rating: 4.4 },

  // Санкт-Петербург
  { id: 'p13', city: 'spb', name: 'Аптека «Первая помощь»', chain: 'Первая помощь', address: 'СПб, Невский пр-т, 88', metro: 'Маяковская', phone: '+7 (812) 111-11-11', hours: 'Пн–Вс: 08:00–23:00', lat: 59.9343, lng: 30.3573, rating: 4.6 },
  { id: 'p14', city: 'spb', name: 'Озерки', chain: 'Озерки', address: 'СПб, Лиговский пр-т, 50', metro: 'Лиговский пр-т', phone: '+7 (812) 222-22-22', hours: 'Круглосуточно', lat: 59.9265, lng: 30.3593, rating: 4.5 },
  { id: 'p15', city: 'spb', name: 'Аптека «Радуга»', chain: 'Радуга', address: 'СПб, Большой пр-т П.С., 72', metro: 'Петроградская', phone: '+7 (812) 333-33-33', hours: 'Пн–Вс: 09:00–22:00', lat: 59.9659, lng: 30.3033, rating: 4.4 },
  { id: 'p16', city: 'spb', name: 'Аптека «Невис»', chain: 'Невис', address: 'СПб, Московский пр-т, 165', metro: 'Электросила', phone: '+7 (812) 444-44-44', hours: 'Пн–Вс: 08:00–22:00', lat: 59.8769, lng: 30.3196, rating: 4.5 },
  { id: 'p17', city: 'spb', name: 'Доктор Столетов', chain: 'Доктор Столетов', address: 'СПб, Каменноостровский пр-т, 36', metro: 'Петроградская', phone: '+7 (812) 555-55-55', hours: 'Пн–Вс: 09:00–21:00', lat: 59.9712, lng: 30.3110, rating: 4.6 },
  { id: 'p18', city: 'spb', name: 'ГосАптека', chain: 'ГосАптека', address: 'СПб, ул. Восстания, 15', metro: 'Площадь Восстания', phone: '+7 (812) 666-66-66', hours: 'Пн–Сб: 08:00–22:00', lat: 59.9347, lng: 30.3608, rating: 4.3 },
  { id: 'p19', city: 'spb', name: 'Аптека «Лекарь»', chain: 'Лекарь', address: 'СПб, Гражданский пр-т, 41', metro: 'Академическая', phone: '+7 (812) 777-77-77', hours: 'Круглосуточно', lat: 60.0145, lng: 30.3956, rating: 4.4 },
  { id: 'p20', city: 'spb', name: 'Будь Здоров СПб', chain: 'Будь Здоров', address: 'СПб, пр-т Просвещения, 80', metro: 'Проспект Просвещения', phone: '+7 (812) 888-88-88', hours: 'Пн–Вс: 08:00–22:00', lat: 60.0518, lng: 30.3325, rating: 4.5 },
];

// Helper to build prices for each med per city
const priceVariation = (base, count, pharmacyIds) => {
  return pharmacyIds.slice(0, count).map((pid, i) => ({
    pharmacyId: pid,
    price: Math.round((base * (0.85 + Math.random() * 0.4)) / 5) * 5,
    qty: Math.floor(Math.random() * 30) + 1,
  }));
};

const MSK_IDS = ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10','p11','p12'];
const SPB_IDS = ['p13','p14','p15','p16','p17','p18','p19','p20'];

export const MEDICATIONS = [
  { slug: 'paracetamol-500mg', name: 'Парацетамол', form: 'Таблетки 500 мг', pack: '20 шт', manufacturer: 'Фармстандарт-Лексредства', country: 'Россия', mnn: 'Парацетамол', ru: 'ЛП-001234', gtin: '4607125831234', category: 'obezbolivayuschie', rx: false, basePrice: 45,
    description: 'Анальгезирующее ненаркотическое и жаропонижающее средство. Применяется при болевом синдроме слабой и умеренной выраженности и при лихорадке.',
    indications: ['Головная боль', 'Зубная боль', 'Мигрень', 'Боли в спине', 'Артралгия', 'Миалгия', 'Невралгия', 'Лихорадочный синдром при простудных заболеваниях'],
    contraindications: ['Гиперчувствительность', 'Тяжёлые нарушения функции печени', 'Возраст до 6 лет'],
    storage: 'В сухом, тёмном месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop' },
  { slug: 'ibuprofen-200mg', name: 'Ибупрофен', form: 'Таблетки п/о 200 мг', pack: '20 шт', manufacturer: 'Борисовский завод', country: 'Беларусь', mnn: 'Ибупрофен', ru: 'ЛП-002345', gtin: '4607125832345', category: 'obezbolivayuschie', rx: false, basePrice: 80,
    description: 'Нестероидный противовоспалительный препарат. Обладает обезболивающим, противовоспалительным и жаропонижающим действием.',
    indications: ['Ревматоидный артрит', 'Остеоартроз', 'Невралгия', 'Миалгия', 'Головная и зубная боль', 'Лихорадочные состояния'],
    contraindications: ['Эрозивно-язвенные заболевания ЖКТ', 'Бронхиальная астма', 'III триместр беременности'],
    storage: 'В сухом, защищённом от света месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1626516940881-1cd9deafe3e7?w=400&h=400&fit=crop' },
  { slug: 'aspirin-cardio', name: 'Аспирин Кардио', form: 'Таблетки п/о 100 мг', pack: '28 шт', manufacturer: 'Bayer', country: 'Германия', mnn: 'Ацетилсалициловая кислота', ru: 'П N016016', gtin: '4607125833456', category: 'serdce', rx: false, basePrice: 280,
    description: 'Антиагрегантное средство. Используется для профилактики тромбоза и инфаркта миокарда.',
    indications: ['Профилактика инфаркта миокарда', 'Профилактика инсульта', 'Нестабильная стенокардия'],
    contraindications: ['Эрозивно-язвенные поражения ЖКТ', 'Геморрагический диатез', 'Беременность (I и III триместр)'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=400&h=400&fit=crop' },
  { slug: 'nurofen', name: 'Нурофен', form: 'Таблетки п/о 200 мг', pack: '20 шт', manufacturer: 'Reckitt Benckiser', country: 'Великобритания', mnn: 'Ибупрофен', ru: 'П N015794', gtin: '4607125834567', category: 'obezbolivayuschie', rx: false, basePrice: 220,
    description: 'Болеутоляющее средство на основе ибупрофена. Действует быстро, эффект наступает в течение 15 минут.',
    indications: ['Головная боль', 'Мигрень', 'Боль в спине', 'Менструальная боль', 'Простудные заболевания'],
    contraindications: ['Язвенная болезнь', 'Бронхиальная астма', 'Тяжёлая печёночная недостаточность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=400&fit=crop' },
  { slug: 'citramon-p', name: 'Цитрамон П', form: 'Таблетки', pack: '10 шт', manufacturer: 'Фармстандарт', country: 'Россия', mnn: 'Парацетамол + Кофеин + АСК', ru: 'ЛС-000123', gtin: '4607125835678', category: 'obezbolivayuschie', rx: false, basePrice: 35,
    description: 'Комбинированный анальгетик. Применяется при болевом синдроме различной локализации.',
    indications: ['Головная боль', 'Зубная боль', 'Мигрень', 'Невралгия', 'Миалгия'],
    contraindications: ['Эрозивно-язвенные поражения ЖКТ', 'Глаукома', 'Беременность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop' },
  { slug: 'kagocel', name: 'Кагоцел', form: 'Таблетки 12 мг', pack: '10 шт', manufacturer: 'НИАРМЕДИК ПЛЮС', country: 'Россия', mnn: 'Кагоцел', ru: 'ЛС-002577', gtin: '4607125836789', category: 'ot-prostudy', rx: false, basePrice: 320,
    description: 'Противовирусное средство. Индуктор синтеза интерферонов.',
    indications: ['Лечение и профилактика гриппа', 'ОРВИ', 'Герпес у взрослых'],
    contraindications: ['Беременность', 'Период лактации', 'Дети до 3 лет', 'Дефицит лактазы'],
    storage: 'В сухом, защищённом от света месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop' },
  { slug: 'arbidol', name: 'Арбидол', form: 'Капсулы 100 мг', pack: '20 шт', manufacturer: 'Отисифарм', country: 'Россия', mnn: 'Умифеновир', ru: 'ЛП-001114', gtin: '4607125837890', category: 'ot-prostudy', rx: false, basePrice: 480,
    description: 'Противовирусное средство. Специфически подавляет вирусы гриппа А и В.',
    indications: ['Грипп А и В', 'ОРВИ', 'Тяжёлый острый респираторный синдром'],
    contraindications: ['Гиперчувствительность', 'Возраст до 6 лет'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&h=400&fit=crop' },
  { slug: 'teraflu', name: 'ТераФлю', form: 'Порошок для приготовления раствора', pack: '10 пак.', manufacturer: 'GSK', country: 'Швейцария', mnn: 'Парацетамол + Фенирамин + Фенилэфрин', ru: 'П N015127', gtin: '4607125838901', category: 'ot-prostudy', rx: false, basePrice: 420,
    description: 'Комбинированный препарат для симптоматического лечения простуды и гриппа.',
    indications: ['ОРВИ', 'Грипп', 'Озноб', 'Лихорадка', 'Головная боль'],
    contraindications: ['Артериальная гипертензия', 'Сахарный диабет', 'Глаукома'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop' },
  { slug: 'ingavirin', name: 'Ингавирин', form: 'Капсулы 90 мг', pack: '7 шт', manufacturer: 'Валента Фарм', country: 'Россия', mnn: 'Имидазолилэтанамид пентандиовой кислоты', ru: 'ЛСР-006330', gtin: '4607125839012', category: 'ot-prostudy', rx: false, basePrice: 580,
    description: 'Противовирусное средство широкого спектра действия.',
    indications: ['Грипп А и B', 'ОРВИ (парагрипп, аденовирусная инфекция)'],
    contraindications: ['Беременность', 'Кормление грудью', 'Возраст до 18 лет'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop' },
  { slug: 'vitamin-d3-2000', name: 'Витамин D3 2000 МЕ', form: 'Капсулы', pack: '60 шт', manufacturer: 'Solgar', country: 'США', mnn: 'Колекальциферол', ru: 'СГР-001-077', gtin: '4607125840123', category: 'vitaminy-bady', rx: false, basePrice: 850,
    description: 'БАД к пище. Источник витамина D3 для поддержания здоровья костей и иммунитета.',
    indications: ['Профилактика дефицита витамина D', 'Поддержка иммунитета', 'Здоровье костей'],
    contraindications: ['Индивидуальная непереносимость', 'Гиперкальциемия'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=400&fit=crop' },
  { slug: 'magnij-b6', name: 'Магний B6', form: 'Таблетки п/о', pack: '50 шт', manufacturer: 'Sanofi', country: 'Франция', mnn: 'Магния лактат + Пиридоксин', ru: 'П N013203', gtin: '4607125841234', category: 'nervnaya', rx: false, basePrice: 690,
    description: 'Препарат для восполнения дефицита магния и витамина B6.',
    indications: ['Дефицит магния', 'Раздражительность', 'Нарушения сна', 'Мышечные спазмы'],
    contraindications: ['Тяжёлая почечная недостаточность', 'Фенилкетонурия'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=400&fit=crop' },
  { slug: 'omega-3', name: 'Омега-3', form: 'Капсулы 1000 мг', pack: '60 шт', manufacturer: 'Doppelherz', country: 'Германия', mnn: 'Рыбий жир', ru: 'СГР-002-056', gtin: '4607125842345', category: 'vitaminy-bady', rx: false, basePrice: 720,
    description: 'БАД. Источник полиненасыщенных жирных кислот для поддержки сердца и сосудов.',
    indications: ['Поддержка сердечно-сосудистой системы', 'Здоровье мозга', 'Эластичность сосудов'],
    contraindications: ['Индивидуальная непереносимость', 'Гемофилия'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop' },
  { slug: 'smekta', name: 'Смекта', form: 'Порошок для приготовления суспензии', pack: '10 пак.', manufacturer: 'Beaufour Ipsen', country: 'Франция', mnn: 'Смектит диоктаэдрический', ru: 'П N011126', gtin: '4607125843456', category: 'zhkt', rx: false, basePrice: 190,
    description: 'Противодиарейное средство природного происхождения.',
    indications: ['Острая и хроническая диарея', 'Изжога', 'Вздутие живота'],
    contraindications: ['Кишечная непроходимость', 'Непереносимость фруктозы'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop' },
  { slug: 'enterosgel', name: 'Энтеросгель', form: 'Паста для приёма внутрь', pack: '225 г', manufacturer: 'ТНК Силма', country: 'Россия', mnn: 'Полиметилсилоксана полигидрат', ru: 'Р N003719', gtin: '4607125844567', category: 'zhkt', rx: false, basePrice: 480,
    description: 'Энтеросорбент. Применяется при острых и хронических интоксикациях.',
    indications: ['Острые отравления', 'Кишечные инфекции', 'Аллергии', 'Дисбактериоз'],
    contraindications: ['Атония кишечника'],
    storage: 'При температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=400&fit=crop' },
  { slug: 'omeprazol-20mg', name: 'Омепразол', form: 'Капсулы 20 мг', pack: '30 шт', manufacturer: 'Озон', country: 'Россия', mnn: 'Омепразол', ru: 'ЛП-001234', gtin: '4607125845678', category: 'zhkt', rx: false, basePrice: 95,
    description: 'Ингибитор протонной помпы. Снижает секрецию соляной кислоты в желудке.',
    indications: ['Язвенная болезнь желудка и ДПК', 'Рефлюкс-эзофагит', 'Гастрит'],
    contraindications: ['Беременность', 'Период лактации', 'Возраст до 18 лет'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1626516940881-1cd9deafe3e7?w=400&h=400&fit=crop' },
  { slug: 'kardiomagnyl', name: 'Кардиомагнил', form: 'Таблетки 75 мг + 15.2 мг', pack: '100 шт', manufacturer: 'Takeda', country: 'Дания', mnn: 'АСК + Магния гидроксид', ru: 'П N013875', gtin: '4607125846789', category: 'serdce', rx: false, basePrice: 380,
    description: 'Антиагрегантный препарат для профилактики сердечно-сосудистых заболеваний.',
    indications: ['Профилактика тромбоза', 'Нестабильная стенокардия', 'Профилактика инсульта'],
    contraindications: ['Геморрагический диатез', 'Язвенная болезнь', 'Тяжёлая почечная недостаточность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=400&h=400&fit=crop' },
  { slug: 'concor-5mg', name: 'Конкор', form: 'Таблетки п/о 5 мг', pack: '50 шт', manufacturer: 'Merck', country: 'Германия', mnn: 'Бисопролол', ru: 'П N011693', gtin: '4607125847890', category: 'serdce', rx: true, basePrice: 380,
    description: 'Селективный β1-адреноблокатор. Снижает частоту сердечных сокращений и АД.',
    indications: ['Артериальная гипертензия', 'ИБС', 'Хроническая сердечная недостаточность'],
    contraindications: ['Острая сердечная недостаточность', 'AV-блокада II–III степени', 'Бронхиальная астма'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop' },
  { slug: 'zodak', name: 'Зодак', form: 'Таблетки п/о 10 мг', pack: '30 шт', manufacturer: 'Zentiva', country: 'Чехия', mnn: 'Цетиризин', ru: 'П N012809', gtin: '4607125848901', category: 'allergiya', rx: false, basePrice: 280,
    description: 'Антигистаминный препарат II поколения для лечения аллергии.',
    indications: ['Аллергический ринит', 'Крапивница', 'Поллиноз', 'Атопический дерматит'],
    contraindications: ['Беременность', 'Лактация', 'Тяжёлая почечная недостаточность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=400&fit=crop' },
  { slug: 'suprastin', name: 'Супрастин', form: 'Таблетки 25 мг', pack: '20 шт', manufacturer: 'Egis', country: 'Венгрия', mnn: 'Хлоропирамин', ru: 'П N012113', gtin: '4607125849012', category: 'allergiya', rx: false, basePrice: 145,
    description: 'Антигистаминный препарат I поколения с выраженным противоаллергическим действием.',
    indications: ['Крапивница', 'Сывороточная болезнь', 'Сезонный и круглогодичный аллергический ринит'],
    contraindications: ['Глаукома', 'Аденома простаты', 'Беременность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop' },
  { slug: 'amoksiklav-625', name: 'Амоксиклав', form: 'Таблетки п/о 500 мг + 125 мг', pack: '14 шт', manufacturer: 'Sandoz', country: 'Словения', mnn: 'Амоксициллин + Клавулановая кислота', ru: 'П N012124', gtin: '4607125850123', category: 'antibiotiki', rx: true, basePrice: 420,
    description: 'Антибиотик широкого спектра действия из группы пенициллинов.',
    indications: ['Инфекции верхних и нижних дыхательных путей', 'Инфекции мочевыводящих путей', 'Инфекции кожи и мягких тканей'],
    contraindications: ['Гиперчувствительность к β-лактамным антибиотикам', 'Холестатическая желтуха в анамнезе'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop' },
  { slug: 'azitromicin', name: 'Азитромицин', form: 'Капсулы 500 мг', pack: '3 шт', manufacturer: 'Озон', country: 'Россия', mnn: 'Азитромицин', ru: 'ЛП-001876', gtin: '4607125851234', category: 'antibiotiki', rx: true, basePrice: 165,
    description: 'Антибиотик-макролид широкого спектра действия.',
    indications: ['Инфекции дыхательных путей', 'ЛОР-инфекции', 'Инфекции кожи', 'Урогенитальные инфекции'],
    contraindications: ['Тяжёлые нарушения функции печени', 'Гиперчувствительность к макролидам'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1626516940881-1cd9deafe3e7?w=400&h=400&fit=crop' },
  { slug: 'aquamaris', name: 'Аква Марис', form: 'Спрей назальный', pack: '30 мл', manufacturer: 'Jadran', country: 'Хорватия', mnn: 'Морская вода', ru: 'П N011533', gtin: '4607125852345', category: 'mat-i-ditya', rx: false, basePrice: 280,
    description: 'Изотонический раствор морской воды для гигиены и увлажнения слизистой носа.',
    indications: ['Профилактика и лечение ринита', 'Гигиена полости носа', 'Уход за носиком ребёнка'],
    contraindications: ['Индивидуальная непереносимость'],
    storage: 'При температуре от 5 до 25 °C',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=400&fit=crop' },
  { slug: 'glycine-100', name: 'Глицин', form: 'Таблетки подъязычные 100 мг', pack: '50 шт', manufacturer: 'Биотики', country: 'Россия', mnn: 'Глицин', ru: 'Р N002847', gtin: '4607125853456', category: 'nervnaya', rx: false, basePrice: 85,
    description: 'Метаболическое средство. Улучшает обменные процессы в тканях мозга.',
    indications: ['Стрессовые состояния', 'Сниженная умственная работоспособность', 'Нарушения сна'],
    contraindications: ['Индивидуальная непереносимость'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=400&fit=crop' },
  { slug: 'afobazol', name: 'Афобазол', form: 'Таблетки 10 мг', pack: '60 шт', manufacturer: 'Отисифарм', country: 'Россия', mnn: 'Фабомотизол', ru: 'ЛС-000861', gtin: '4607125854567', category: 'nervnaya', rx: false, basePrice: 480,
    description: 'Анксиолитик небензодиазепинового ряда. Уменьшает тревожность.',
    indications: ['Тревожные расстройства', 'Неврастения', 'Расстройства адаптации'],
    contraindications: ['Беременность', 'Период лактации', 'Возраст до 18 лет'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop' },
  { slug: 'essentiale-forte', name: 'Эссенциале Форте Н', form: 'Капсулы 300 мг', pack: '30 шт', manufacturer: 'Sanofi', country: 'Франция', mnn: 'Фосфолипиды', ru: 'П N011496', gtin: '4607125855678', category: 'zhkt', rx: false, basePrice: 850,
    description: 'Гепатопротектор. Восстанавливает структуру и функции клеток печени.',
    indications: ['Хронический гепатит', 'Цирроз печени', 'Жировая дистрофия печени', 'Токсические поражения'],
    contraindications: ['Гиперчувствительность', 'Возраст до 12 лет'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop' },
  { slug: 'tizin', name: 'Тизин Ксило', form: 'Спрей назальный 0.1%', pack: '10 мл', manufacturer: 'Famar Orleans', country: 'Франция', mnn: 'Ксилометазолин', ru: 'П N015456', gtin: '4607125856789', category: 'ot-prostudy', rx: false, basePrice: 195,
    description: 'Сосудосуживающее средство для местного применения в ЛОР-практике.',
    indications: ['Острый ринит', 'Синусит', 'Поллиноз', 'Отит'],
    contraindications: ['Артериальная гипертензия', 'Тахикардия', 'Глаукома'],
    storage: 'При температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=400&fit=crop' },
  { slug: 'bepanten', name: 'Бепантен', form: 'Крем для наружного применения 5%', pack: '30 г', manufacturer: 'Bayer', country: 'Германия', mnn: 'Декспантенол', ru: 'П N015723', gtin: '4607125857890', category: 'kozha', rx: false, basePrice: 420,
    description: 'Стимулятор регенерации тканей. Применяется при опрелостях и раздражении кожи.',
    indications: ['Сухость кожи', 'Опрелости у грудных детей', 'Трещины сосков', 'Ожоги'],
    contraindications: ['Гиперчувствительность'],
    storage: 'При температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop' },
  { slug: 'vizin', name: 'Визин Классический', form: 'Капли глазные 0.05%', pack: '15 мл', manufacturer: 'Johnson & Johnson', country: 'Канада', mnn: 'Тетризолин', ru: 'П N015709', gtin: '4607125858901', category: 'glaza', rx: false, basePrice: 380,
    description: 'Сосудосуживающие глазные капли. Уменьшают красноту и отёк конъюнктивы.',
    indications: ['Покраснение глаз', 'Отёк конъюнктивы', 'Раздражение от пыли, дыма'],
    contraindications: ['Закрытоугольная глаукома', 'Возраст до 2 лет'],
    storage: 'При температуре от 4 до 30 °C',
    image: 'https://images.unsplash.com/photo-1583912267550-d6c2ac3196c0?w=400&h=400&fit=crop' },
  { slug: 'mukaltin', name: 'Мукалтин', form: 'Таблетки 50 мг', pack: '20 шт', manufacturer: 'Фармстандарт', country: 'Россия', mnn: 'Алтея корней экстракт', ru: 'Р N003581', gtin: '4607125859012', category: 'ot-prostudy', rx: false, basePrice: 35,
    description: 'Отхаркивающее средство растительного происхождения.',
    indications: ['Кашель при острых и хронических заболеваниях органов дыхания'],
    contraindications: ['Язвенная болезнь', 'Гиперчувствительность'],
    storage: 'В сухом месте при температуре не выше 25 °C',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop' },
];

// Build prices structure: { medSlug: { msk: [{pharmacyId, price, qty}], spb: [...] } }
function seededPrice(seed, base) {
  const x = Math.sin(seed) * 10000;
  const v = x - Math.floor(x);
  return Math.round((base * (0.85 + v * 0.4)) / 5) * 5;
}
function seededQty(seed) {
  const x = Math.sin(seed * 1.7) * 10000;
  const v = x - Math.floor(x);
  return Math.floor(v * 30) + 1;
}

export const PRICES = MEDICATIONS.reduce((acc, med, mIdx) => {
  const buildFor = (ids) => ids.map((pid, i) => ({
    pharmacyId: pid,
    price: seededPrice(mIdx * 100 + i + 1, med.basePrice),
    qty: seededQty(mIdx * 100 + i + 7),
  }));
  acc[med.slug] = {
    msk: buildFor(MSK_IDS),
    spb: buildFor(SPB_IDS),
  };
  return acc;
}, {});

// Aliases for analogs (by MNN)
export const getAnalogs = (med) => MEDICATIONS.filter(m => m.slug !== med.slug && (m.mnn === med.mnn || m.category === med.category)).slice(0, 4);

export const findMedBySlug = (slug) => MEDICATIONS.find(m => m.slug === slug);
export const findPharmacyById = (id) => PHARMACIES.find(p => p.id === id);
export const pharmaciesByCity = (cityId) => PHARMACIES.filter(p => p.city === cityId);
